apiVersion: v1
description: RAO app
name: rao
sources:
  - https://github.com/stashify/frontend
maintainers:
  - name: RAO Application
    email: ramon@flaps.io
version: 99999.99999.99999
appVersion: 99999.99999.99999
