apiVersion: v1
description: Auth app
name: auth
sources:
  - https://github.com/stashify/frontend
maintainers:
  - name: Auth Application
    email: ramon@flaps.io
version: 99999.99999.99999
appVersion: 99999.99999.99999
