apiVersion: v1
description: Manager Frontend App
name: manager
sources:
- https://github.com/nuclia/frontend
maintainers:
- name: Application
  email: ramon@stashify.cloud
version: 99999.99999.99999
appVersion: 99999.99999.99999
